SPK_NAME = openssl
SPK_VERS = 1.0.2l
SPK_REV = 1
SPK_ICON = src/openssl.jpg

DEPENDS  = cross/openssl

MAINTAINER = HD Stich
DESCRIPTION = OpenSSL
DISPLAY_NAME = OpenSSL

HOMEPAGE   = 
LICENSE    =

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
