SPK_NAME = zlib
SPK_VERS = 1.2.11
SPK_REV = 1
SPK_ICON = src/zlib.png

DEPENDS  = cross/zlib

MAINTAINER = HD Stich
DESCRIPTION = zlib libraries
DISPLAY_NAME = zlib

HOMEPAGE   = 
LICENSE    =

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
