PKG_NAME = cffi
PKG_VERS = 1.10.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://pypi.python.org/packages/5b/b9/790f8eafcdab455bcd3bd908161f802c9ce5adbf702a83aa7712fcc345b7
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/pycparser cross/libffi

HOMEPAGE = http://cffi.readthedocs.org
COMMENT  = Foreign Function Interface for Python calling C code
LICENSE  = MIT

include ../../mk/spksrc.python-module.mk
