SPK_NAME = sqlite
SPK_VERS = 3160200
SPK_REV = 1
SPK_ICON = src/sqlite.png

DEPENDS  = cross/sqlite

MAINTAINER = HD Stich
DESCRIPTION = sqlite
DISPLAY_NAME = sqlite

HOMEPAGE   = 
LICENSE    =

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
