PKG_NAME = pycparser
PKG_VERS = 2.18
PKG_EXT = tar.gz
PKG_DIST_NAME = release_v$(PKG_VERS).$(PKG_EXT)
PKG_DIST_FILE = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/eliben/pycparser/archive
PKG_DIR = $(PKG_NAME)-release_v$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://github.com/eliben/pycparser
COMMENT  = pycparser is a complete parser of the C language
LICENSE  = BSD

include ../../mk/spksrc.python-module.mk
